version: '3'
services:
  myapp:
    build: .
    container_name: myapp
    ports:
      - 5000:5000
    
  mongodata:
    image: mongo
    container_name: mongodata
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    ports:
      - 27017:27017
    depends_on:
      - myapp
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_SERVER=mongodata